AWSTemplateFormatVersion: 2010-09-09
Description: Starter template for ECS

Parameters:
  Image:
    Type: String
    Description: URI of image you would like to use

Resources:

  EcsCluster:
    Type: AWS::ECS::Cluster

  DefaultRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
              - ecs.amazonaws.com
              - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  # Specifies type of loadbalancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups:
        - sg-624c6c37
      Subnets:
        - subnet-3acb3671
        - subnet-09183753
      Type: application

  HelloWorldTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckPath: "/health"
      HealthCheckPort: 5000
      HealthCheckProtocol: HTTP
      Port: 5000
      Protocol: HTTP
      TargetType: ip
      VpcId: vpc-aded5dd4

  HelloWorldListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Order: 1
          TargetGroupArn: !Ref HelloWorldTargetGroup
          Type: forward
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 5000
      Protocol: HTTP
    DependsOn:
      - HelloWorldTargetGroup
  
  HelloWorldService:
    Type: AWS::ECS::Service
    DependsOn: HelloWorldListener
    Properties:
      Cluster: !Ref EcsCluster
      DeploymentController:
        Type: ECS
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 50
      LaunchType: FARGATE
      LoadBalancers:
        -
          ContainerName: hello-world
          ContainerPort: 5000
          TargetGroupArn: !Ref HelloWorldTargetGroup
      NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: ENABLED
            SecurityGroups:
              -  sg-624c6c37
            Subnets:
              - subnet-09183753
              - subnet-3acb3671
      TaskDefinition: !Ref HelloWorldTaskDefinition

  HelloWorldLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7

  HelloWorldTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        -
          Name: hello-world
          Essential: true
          Image: !Ref Image
          LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: !Ref HelloWorldLogGroup
                awslogs-stream-prefix: hello-world-container
                awslogs-region: eu-west-1 #!Ref AWS::Region
          PortMappings:
            -
              ContainerPort: 5000
              HostPort: 5000
              Protocol: tcp
      Cpu: '1024'
      ExecutionRoleArn: !Ref DefaultRole
      Memory: '3072' #3072
      NetworkMode: awsvpc
      RequiresCompatibilities:
        -  FARGATE
      TaskRoleArn: !Ref DefaultRole