AWSTemplateFormatVersion: 2010-09-09
Description: Starter template for ECS

Parameters:
  Image:
    Type: String
    Description: URI of image you would like to use

Resources:

  EcsCluster:
    Type: AWS::ECS::Cluster

  DefaultRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
              - ecs.amazonaws.com
              - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess


  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups:
        - sg-624c6c37
      Subnets:
        - subnet-3acb3671
        - subnet-09183753
      Type: application

  HelloWorldTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckPath: /health
      HealthCheckPort: 8080
      HealthCheckProtocol: HTTP
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      VpcId: vpc-aded5dd4


  HelloWorldListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Order: 1
          TargetGroupArn: !Ref HelloWorldTargetGroup
          Type: forward
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 8080
      Protocol: HTTP
    DependsOn:
      - HelloWorldTargetGroup

  HelloWorldService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref EcsCluster
      DeploymentController:
        Type: ECS
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 60
      LaunchType: FARGATE
      LoadBalancers:
        -
          ContainerName: hello-world
          ContainerPort: 8080
          TargetGroupArn: !Ref HelloWorldTargetGroup
      NetworkConfiguration:
          AwsvpcConfiguration:
            SecurityGroups: sg-624c6c37
            Subnets:
              - arn:aws:ec2:eu-west-1:940062133499:subnet/subnet-09183753
              - arn:aws:ec2:eu-west-1:940062133499:subnet/subnet-3acb3671b
      TaskDefinition: !Ref HelloWorldTaskDefinition

  HelloWorldLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7

  HelloWorldTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        -
          Name: hello-world
          Essential: true
          Image: !Ref Image
          LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: !Ref HelloWorldLogGroup
                awslogs-stream-prefix: hello-world-container
                awslogs-region: !Ref AWS::Region
          PortMappings:
            -
              ContainerPort: 8080
              HostPort: 8080
              Protocol: tcp
      Cpu: '256'
      ExecutionRoleArn: !Ref DefaultRole
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        -  FARGATE
      TaskRoleArn: !Ref DefaultRole
